server:
  port: 1010
spring:
  application:
    name: config-service
  profiles:
    active: native
  cloud:
    zookeeper:
      discovery:
        enabled: true
      connect-string: 192.168.1.3:2181
    config:
      server:
        native:
          search-locations: classpath:/configs
