server:
  port: 1000
spring:
  application:
    name: gateway
  cloud:
    zookeeper:
      discovery:
        enabled: true
      connect-string: 192.168.1.3:2181
    gateway:
      routes:
        - id: sys-service
          uri: lb://sys-service
          predicates:
            - Path=/sys/**
          filters:
            - StripPrefix=1
